# Generated by Django 5.0.6 on 2024-07-22 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memtrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=3, null=True)),
                ('loans', models.CharField(blank=True, max_length=30, null=True)),
                ('cycle', models.IntegerField(blank=True, null=True)),
                ('gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('trx_no', models.CharField(blank=True, max_length=8, null=True)),
                ('ses_date', models.DateField()),
                ('app_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.CharField(blank=True, default='A', max_length=10, null=True)),
                ('type', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
