# Generated by Django 5.0.6 on 2024-07-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_interestrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrate',
            name='debit_account',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
