# Generated by Django 5.0.6 on 2024-07-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_interestrate_debit_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='ac_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='memtrans',
            name='gl_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
