# Generated by Django 5.0.6 on 2024-07-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_memtrans_ac_no_alter_memtrans_gl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='ac_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='memtrans',
            name='gl_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
