# Generated by Django 5.0.6 on 2024-07-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_memtrans_ac_no_alter_memtrans_gl_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='memtrans',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
