# Generated by Django 5.0.6 on 2024-07-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_memtrans_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestrate',
            old_name='debit_account',
            new_name='glno_debit_account',
        ),
        migrations.AddField(
            model_name='interestrate',
            name='acno_debit_account',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
