# Generated by Django 5.0.6 on 2024-08-01 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_rename_debit_account_interestrate_glno_debit_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrate',
            name='ses_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
