# Generated by Django 5.0.6 on 2024-08-15 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_memtrans_app_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='app_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
