# Generated by Django 5.0.6 on 2024-08-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_memtrans_sys_date_alter_memtrans_app_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='memtrans',
            name='account_type',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
