# Generated by Django 5.0.6 on 2024-07-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sign',
            field=models.ImageField(default='images/avatar.jpg', upload_to='sign/customer'),
        ),
    ]
