# Generated by Django 5.0.6 on 2024-09-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sms',
            field=models.BooleanField(default=False),
        ),
    ]
