# Generated by Django 5.0.6 on 2024-07-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_code', models.CharField(max_length=5)),
                ('branch_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=100)),
                ('contact_phone_no', models.CharField(max_length=100)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('system_date_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('license_key', models.CharField(max_length=50)),
                ('session_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
