# Generated by Django 5.0.6 on 2024-08-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='branch_code',
            field=models.CharField(max_length=5),
        ),
    ]
