# Generated by Django 5.0.6 on 2024-07-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_admin', '0009_rename_writ_off_ac_no_account_writ_off_cr_ac_no_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('gl_no', models.CharField(max_length=20)),
                ('ac_no', models.CharField(max_length=20)),
                ('cycle', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('trx_date', models.DateField()),
                ('trx_type', models.CharField(max_length=50)),
                ('trx_no', models.CharField(max_length=50)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_gl_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gl_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=20, null=True)),
                ('cycle', models.IntegerField(blank=True, null=True)),
                ('appli_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payment_freq', models.CharField(blank=True, choices=[('365', 'Daily'), ('52', 'Weekly'), ('26', 'Bi-Weekly'), ('13', 'Once Every 4 Weeks'), ('12', 'Monthly'), ('6', 'Bi-Monthly'), ('1.35', '9 Monthly'), ('1.22', '10 Monthly'), ('1.11', '11 Monthly'), ('17.38', '3 Weekly'), ('13.03', '4 Weekly'), ('10.43', '5 Weekly'), ('24.33', 'Half Monthly'), ('3.04', 'Quarterly'), ('1', 'Yearly')], max_length=10, null=True)),
                ('num_install', models.PositiveIntegerField()),
                ('interest_calculation_method', models.CharField(blank=True, choices=[('1', 'Compound Interest'), ('2', 'Decline Balance - Daily Balance'), ('3', 'Decline Balance - Equal Due'), ('4', 'Decline Balance - Equal Installment'), ('5', 'Decline Balance - Straight Line'), ('6', 'Flat Rate')], max_length=10, null=True)),
                ('approval_status', models.CharField(blank=True, default='F', max_length=1, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('total_loan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numerical_value', models.CharField(blank=True, max_length=20, null=True)),
                ('disb_status', models.CharField(blank=True, default='F', max_length=1, null=True)),
                ('int_to_recev_gl_dr', models.CharField(blank=True, max_length=6, null=True)),
                ('int_to_recev_ac_dr', models.CharField(blank=True, max_length=6, null=True)),
                ('unearned_int_inc_gl', models.CharField(blank=True, max_length=6, null=True)),
                ('unearned_int_inc_ac', models.CharField(blank=True, max_length=6, null=True)),
                ('interest_gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('interest_ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('pen_gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('pen_ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('business_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.business_sector')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('loan_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.account_officer')),
            ],
        ),
    ]
