# Generated by Django 5.0.6 on 2024-09-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='trx_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='interest_calculation_method',
            field=models.CharField(blank=True, choices=[('1', 'Compound Interest'), ('2', 'Decline Balance - Daily Balance'), ('3', 'Decline Balance - Equal Installment'), ('4', 'Decline Balance - Equal Due'), ('5', 'Decline Balance - Straight Line'), ('6', 'Flat Rate')], max_length=10, null=True),
        ),
    ]
