# Generated by Django 5.0.6 on 2024-09-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loans_trx_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='trx_type',
        ),
    ]
