# Generated by Django 5.0.6 on 2024-09-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loans_trx_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhist',
            name='trx_destription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
