# Generated by Django 5.0.6 on 2024-09-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loanhist_trx_destription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanhist',
            old_name='trx_destription',
            new_name='trx_naration',
        ),
    ]
