# Generated by Django 5.0.6 on 2024-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_rename_trx_destription_loanhist_trx_naration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanhist',
            name='trx_date',
            field=models.DateTimeField(),
        ),
    ]
