# Generated by Django 4.2.6 on 2023-10-31 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Id_card_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.region')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_name', models.CharField(max_length=80, unique=True)),
                ('gl_no', models.CharField(max_length=10, unique=True)),
                ('account_type', models.PositiveIntegerField(blank=True, choices=[(1, 'Assets'), (2, 'Liabilities'), (3, 'Equity'), (4, 'Expenses'), (5, 'Income')], default='1')),
                ('currency', models.PositiveIntegerField(blank=True, choices=[(1, 'Us dollar'), (2, 'Nigeria')], default='1')),
                ('double_entry_type', models.PositiveIntegerField(blank=True, choices=[(1, 'Debit & Credit'), (2, 'Credit'), (3, 'Debit')], default='1')),
                ('is_non_financial', models.BooleanField(default=False)),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_admin.account')),
            ],
        ),
    ]
