# Generated by Django 4.2.6 on 2023-10-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_officer',
            name='user',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
