# Generated by Django 5.0.1 on 2024-01-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0004_account_int_to_recev_ac_dr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_type', models.CharField(blank=True, choices=[('LOANS', 'Loans'), ('SAVINGS', 'Savings'), ('SHARES', 'Shares'), ('FIXED_DEPOSIT', 'Fixed Deposit'), ('INCOMES', 'Incomes'), ('EXPENSE', 'Expense'), ('BANK_PLACEMENTS', 'Bank Placements'), ('DISCOUNT_INSTRUMENTS', 'Discount Instruments'), ('NONE', 'NONE')], default='NONE', max_length=20)),
            ],
        ),
    ]
