# Generated by Django 5.0.1 on 2024-01-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0005_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.product_type'),
        ),
    ]
