# Generated by Django 5.0.1 on 2024-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0008_alter_product_type_internal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='writ_off_ac_no',
            new_name='writ_off_cr_ac_no',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='writ_off_gl_no',
            new_name='writ_off_cr_gl_no',
        ),
        migrations.AddField(
            model_name='account',
            name='writ_off_dr_ac_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='writ_off_dr_gl_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='internal_type',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
