# Generated by Django 5.0.6 on 2024-07-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0009_rename_writ_off_ac_no_account_writ_off_cr_ac_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_no', models.CharField(max_length=6, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('debit_account', models.CharField(max_length=6)),
            ],
        ),
    ]
