# Generated by Django 5.0.6 on 2024-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0010_interestrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_provisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the arrears range (e.g., '0-30 days', '31-60 days')", max_length=100)),
                ('min_days', models.IntegerField(help_text='Minimum days of arrears')),
                ('max_days', models.IntegerField(help_text='Maximum days of arrears')),
                ('provision_rate', models.DecimalField(decimal_places=2, help_text='Provision rate for this arrears range (%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Arrears Range',
                'verbose_name_plural': 'Arrears Ranges',
                'ordering': ['min_days'],
            },
        ),
    ]
