# Generated by Django 5.0.6 on 2024-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0011_loan_provisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Loan_provisions',
        ),
    ]
